### ISSUE TITLE
Create Carousel for Tours and correct the placement of headings

### ISSUE THREAD

**Issue by Mahak008** [gn009/hack#39]

**Comment by gn009** [comment]
> _No description provided._

hey @Mahak008  would you like to work on this issue?

**Comment by Mahak008** [comment]
> > _No description provided._
> 
> hey @Mahak008 would you like to work on this issue?

Yes, please assign this issue to me.

**Comment by gn009** [comment]
> > > _No description provided._
> > 
> > 
> > hey @Mahak008 would you like to work on this issue?
> 
> Yes, please assign this issue to me.

Go ahead @Mahak008 don't forget to sync fork the repo before opening the PR
