### ISSUE TITLE
Bug: Go to top button is not at the right place

### ISSUE THREAD

**Issue by sshsrn** [gn009/hack#51]
The Go to top button is not at the right place and is static in the top of the page.
![image](https://user-images.githubusercontent.com/62781914/197382397-ef9f8815-005a-48c9-b719-72b0320a627c.png)

**Comment by sshsrn** [comment]
@gn009 Kindly assign this issue to me so that I can work on it!

**Comment by gn009** [comment]
> @gn009 Kindly assign this issue to me so that I can work on it!

Yep go ahead @SSHSRN
