### ISSUE TITLE
Inconsistent UI

### ISSUE THREAD

**Issue by sshsrn** [gn009/hack#52]
The UI in the page is not consistent and is also minimalistic. 

![image](https://user-images.githubusercontent.com/62781914/197382481-f8f16c10-c1bc-48c5-8fbb-c1b7a60825b2.png)
![image](https://user-images.githubusercontent.com/62781914/197382528-557287fc-612e-4dc9-97f1-87ac3e47bd33.png)

I would like to redesign the page.

**Comment by sshsrn** [comment]
@gn009, kindly assign me this issue so that I can work on it!

**Comment by gn009** [comment]
> @gn009, kindly assign me this issue so that I can work on it!

Go ahead @SSHSRN
